### ISSUE TITLE
Do you still need butterknife?

### ISSUE THREAD

**Issue by elye** [dlew/android-architecture-counter-sample#1]
Hi Dan, you have use Kotlin, do you still prefer butterknife over Kotlin extension? Just curious, in case you are aware of any deficiency in using Kotlin extension over butterknife...

**Comment by dlew** [comment]
See https://github.com/dlew/android-architecture-counter-sample/pull/4#issuecomment-303543726 for a short discussion on Kotlin extensions. I'm not a fan (yet?).
